blank_issues_enabled: false
contact_links:
  - name: Issue about Magmawm
    url: https://github.com/MagmaWM/MagmaWM/
    about: Make a suggestion or report a bug about Magmawm
  - name: Suggestions or feature request
    url: https://github.com/MagmaWM/MagmaWM/discussions/categories/ideas
    about: Got something you think should change or be added? Search for or start a new discussion!
  - name: Help
    url: https://github.com/MagmaWM/MagmaWM/discussions/categories/q-a
    about: Magmawm not working as you'd expect? Not sure it's a bug? Check the Q&A section!
